### ISSUE TITLE
Node\r No File/Directory :  npx prisma-multischema error

### ISSUE THREAD

**Issue by febrimaulana** [joydip007x/prisma-unify007x#6]
i running npx prisma-multischema and then result error
env: node\r: No such file or directory

whereas i running node -v is show
![image](https://github.com/ajmnz/prisma-import/assets/30101915/96f539a0-d28e-427e-a98f-8e2ea839d813)

**Comment by joydip007x** [comment]
@febrimaulana  Hey, It's not a bug in `prisma-multischema` but rather
[due to a difference in line endings, especially the difference in LF vs. CRLF ( Windows vs Unix SPACING ) 
](https://stackoverflow.com/a/68820477). Unix systems like Linux and macOS use LF , the line feed character, for line breaks by default. Windows, on the other hand, is special and uses CR/LF , carriage return AND line feed character, by default. 

In short ,  The binary executable from package can't be executed because  your **macOS/Linux** ( My guess ,you are using  any Of these) is  having trouble to treat DOS-character.

Fix - (from [StackOverflow Post](https://stackoverflow.com/questions/30344858/node-script-executable-not-working-on-mac-env-node-r-no-such-file-or-directo/68820477#68820477))

1.`brew install dos2unix`  or find [any npm package to do Dos-to-Unix ](https://www.google.com/search?client=firefox-b-d&q=npm+dos2unix)
2.`Run the cmd to Convert Dos2Unix` - `sudo dos2unix  **Path_to_Project_Root**/node_modules/prisma-multischema/bin/run` 

Keep me Updated 👍

Also try checking and changing the files EOF rules to CRLF or LF  ( based on your OS) : 
![image](https://github.com/joydip007x/Prisma-MultiSchema/assets/38793267/7522be40-0896-41e5-8f4e-e8feeeb8603e)
